### ISSUE TITLE
Clarify usage of non-prolog syntax

### ISSUE THREAD

**Issue by rwakulszowa** [simply-logical/simply-logical#19]
https://book.simply-logical.space/src/text/1_part_i/2.1.html

The book gives a following example:
```married;bachelor:-man,adult.```

From what I understand, this example __is not__ a Prolog expression, but uses some fancy theoretical magic language. It would be cool if there was a disclaimer telling people not to copy-paste that into a SWISH environment.
I spend about an hour trying to figure out why my SWI-Prolog rejects this syntax 😕

**Comment by rwakulszowa** [comment]
If you confirm it makes sense, I can send a PR.

**Comment by So-Cool** [comment]
Thanks for pointing this out, @rwakulszowa. We decided to use a different background colour for code blocks that do not contain Prolog.
